baseURL = 'https://eamonncottrell.com/'
languageCode = 'en-us'
title = 'Eamonn Cottrell'
theme = 'eamonn'

enableEmoji = true


[params]
subtitle = "I make tech videos and tutorials. Try my free newsletter ðŸ‘‡"
description = "Eamonn is a COO and YouTuber based in the southeastern United States."
metaimage = "/images/twittercard.jpg"
gtag = "G-YML43Q3HZ7"
images = ["/images/twittercard.jpg"]

[permalinks]
'posts' = '/:slug/'

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = -1
 [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
[[menu.main]]
    name = "Podcasts"
    url = "/podcasts"
    weight = 4
